In [1]:
#import pandas
import pandas as pd

In [3]:
#create pandas series using list
data=[10,20,30,40]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [5]:
#create pandas series using a custom index value
data=[1,2,3,4]
i=['A','B','C','D']
series=pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [7]:
#create pandas series using dictionary
data={'a':10,'b':20,'c':30,'d':40}
series=pd.Series(data)
print(series)

a    10
b    20
c    30
d    40
dtype: int64


In [9]:
series.replace(20,100)

a     10
b    100
c     30
d     40
dtype: int64

In [11]:
#create series using numpy array

Pandas dataframe

In [17]:
#create pandas dataframe from dictionary of lists

In [19]:
import pandas as pd

In [23]:
data={'Name':['Alice','Bob','Mary'],'Age':[25,30,34],'Country':['Usa','India','Russia']}
df=pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     Usa
1    Bob   30   India
2   Mary   34  Russia


In [25]:
#create pandas dataframe from numpy array

In [31]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [33]:
#create a dataframe from a nested list
data=[[1,'Alice',25],[2,'Bob',30],[3,'Mary',34]]
print(data)
df=pd.DataFrame(array,columns=['ID','Name','Age'])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 30], [3, 'Mary', 34]]
   ID  Name  Age
0   1     2    3
1   4     5    6
2   7     8    9


In [35]:
#import data from a csv file and create
iris_df=pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]
